server:
  port: 8081
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSIONID01
        
#授权服务器地址
oauth2-server-url: http://127.0.0.1:8080

#与授权服务器对应的配置
security:
  oauth2:
    client:
      client-id: clientId
      client-secret: 112233
      user-authorization-uri: ${oauth2-server-url}/oauth/authorize
      access-token-uri: ${oauth2-server-url}/oauth/token
    resource:
      jwt:
        key-uri: ${oauth2-server-url}/oauth/token_key
        